### ISSUE TITLE
Introduce a requirements.txt file

### ISSUE THREAD

**Issue by matthias-mayr** [luinardi/hypermapper#27]
I am following the [installation process for hypermapper](https://github.com/luinardi/hypermapper/wiki/Install-HyperMapper). I made a deliberate choice against adding `conda` as a third package source beside `pip` and system packages.

 Is there a specific reason that the dependencies are not collected in a `requirements.txt` file?
I think that doing so would not only make installation process smoother, but also make the repository more standalone from the wiki.

Furthermore, the wiki is somewhat independent from the repository and it would be easier to keep track of new dependencies or specific versions if it is directly defined in the code repository.

**Comment by matthias-mayr** [comment]
I just tried to do that and it's a bit more complicated that expected. When just taking the current dependencies on a new Python3 environment, `GPy` runs into [this issue](https://github.com/pypa/pip/issues/9239).

As suggested here, it can quite easily avoided by installing `numpy` ahead of the rest. So the installation would boil down to
```
pip3 install numpy
python3 -m pip install -r requirements.txt --user
```
This step would not be necessary with environments which already have a `numpy` installation.

Furthermore, I needed to add `cython` to the list - otherwise `sklearn` refuses to install on Ubuntu 18.04. The version that ships in the Ubuntu package repositories (0.26.1) is not sufficient.

**Comment by arturluis** [comment]
Hi @matthias-mayr, 

Thanks for raising this issue and apologies for the delay in getting back to you on this. We recently released HyperMapper on pip. Now, HyperMapper can be installed via `pip install hypermapper` or by cloning the repo and running `pip install .`. Using these commands will ensure the latest version of HM is installed, together with all dependencies. This new installation via pip is preferable to manually installing dependencies, which is why we waited a bit before replying to this issue and have not added the requirements.txt file. Thank you for the suggestion and accompanying PR!
