### ISSUE TITLE
logfile enabled by default

### ISSUE THREAD

**Issue by zabotio** [luinardi/hypermapper#44]
I suppose this is more of a suggestion than an issue.

When clearing out some space on my disk earlier, I found a massive 6.5G log-file from HyperMapper.
From what I gather, HyperMapper has this log-file enabled by default, and seems to accumulate more and more logs over time.

While logging is great for many purposes, perhaps it shouldn't behave this way by default?
My rationale is that most end users probably won't care about the logs, much less accumulated logs from several runs.

Therefore I would like to suggest either disabling the log-file by default, or alternatively disabling the accumulation by default.

If this suggestion is welcome, I'd be happy to create a pull request for it myself, if that is of any help.

**Comment by matthias-mayr** [comment]
I noticed this as well. For my experiments it's only about 50mb per optimization, but right now the ~160 runs still add up to 10GB of disk space.
My personal preference would be to keep the log file, but have a bit less "internal" information by default. It seems like ~95% of the 300000 lines are from the local search and my first guess would be that these lines are only relevant for some users.
Maybe an option to specifically enable verbose logging of the local search could be a good compromise.

**Comment by arturluis** [comment]
Hello @zabotio and @matthias-mayr , 

Thank you for the suggestion. You're right, right now HyperMapper is generating a lot of logging information that makes the logfile take a lot of disk space. We had a discussion about this internally (with @zabotio as well) and I would like to try to summarize it here.

We would like to still generate the logfile by default and append information of different runs into it, rather than overwrite it, so that we can assist users if they run into any issue. However, we can tweak it as @matthias-mayr suggested to make it take massively less space. In short, change how the logging is done so that, by default, HyperMapper logs only a summary of the information we need to pinpoint problems and help users. At the same time, keep in a verbose logging option that can be triggered if anyone wants more detailed logging information. 

For instance, [this line](https://github.com/luinardi/hypermapper/blob/968992396e5d2dec4b0f62b5148c5000d3928a0f/hypermapper/local_search.py#L750) is currently responsible for most of the contents of the logfile, but it does not need to be logged every time. Logging this line on verbose mode only should already reduce the size of the logfile considerably.

@zabotio we will accept your offer. If you can create a PR for this change we would deeply appreciate it. Of course, I can help if you run into any difficulty with the PR, just let me know.

Thank you once again for bringing this to our attention!

**Comment by zabotio** [comment]
Added a pull request for this issue: #46

**Comment by arturluis** [comment]
Thanks @zabotio , the PR has been merged and this has been addressed. The logfile should be much smaller now
